name: Docker Image CI

on:
  pull_request:
    paths:
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test
    - name: Push
      run: |
        docker login docker.pkg.github.com --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        export VERSION=$(docker inspect --format="{{.Config.Labels.version}}" test)
        echo ${VERSION}
        docker tag test docker.pkg.github.com/ekpyron/test/test-image:${VERSION}
        docker push docker.pkg.github.com/ekpyron/test/test-image:${VERSION}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

